package com.tanwir.arc.interceptor;

import java.util.logging.Logger;

/**
 * Built-in interceptor that logs method entry and exit.
 *
 * <p>Activated by the {@link Logged} interceptor binding. Generated by the
 * {@link com.tanwir.arc.processor.ArcBeanProcessor} as part of the {@code _Subclass}
 * when a CDI bean method carries {@code @Logged}.
 *
 * <h2>Log output</h2>
 * <pre>
 * INFO  [arc.interceptor.LoggingInterceptor] → ProductResource.listAll()
 * INFO  [arc.interceptor.LoggingInterceptor] ← ProductResource.listAll() [2 ms] → ArrayList
 * </pre>
 *
 * <h2>Real Quarkus comparison</h2>
 * This interceptor mirrors the structure of real Quarkus interceptors:
 * <ol>
 *   <li>Annotated with {@link Interceptor} — CDI recognises it as an interceptor class</li>
 *   <li>Annotated with {@link Logged} — declares which interceptor binding activates it</li>
 *   <li>Has an {@link AroundInvoke} method — the cross-cutting code</li>
 * </ol>
 * In Quarkus you would additionally add {@code @Priority(Interceptor.Priority.APPLICATION)}
 * to control ordering when multiple interceptors apply to the same method.
 */
@Interceptor
@Logged
public class LoggingInterceptor {

    private static final Logger LOG = Logger.getLogger(LoggingInterceptor.class.getName());

    /**
     * Logs the method name before invocation and the result / duration afterwards.
     *
     * <p>Must call {@link InvocationContext#proceed()} to invoke the target method;
     * skipping it would prevent the real method from running.
     */
    @AroundInvoke
    public Object log(InvocationContext ctx) throws Exception {
        String target = ctx.getTarget().getClass().getSimpleName();
        // Strip "_Subclass" suffix for readability
        if (target.endsWith("_Subclass")) {
            target = target.substring(0, target.length() - "_Subclass".length());
        }
        String method = ctx.getMethodName();
        LOG.info("→ " + target + "." + method + "()");

        long start = System.currentTimeMillis();
        Object result;
        try {
            result = ctx.proceed();
        } catch (Exception e) {
            LOG.warning("✗ " + target + "." + method + "() threw "
                    + e.getClass().getSimpleName() + ": " + e.getMessage());
            throw e;
        }
        long elapsed = System.currentTimeMillis() - start;
        String resultDesc = result == null ? "void"
                : result.getClass().getSimpleName() + (result instanceof java.util.Collection<?> c
                        ? "[" + c.size() + "]" : "");
        LOG.info("← " + target + "." + method + "() [" + elapsed + " ms] → " + resultDesc);
        return result;
    }
}
