package com.tanwir.miniquarkus.processor;

import java.lang.annotation.Annotation;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import org.jboss.jandex.AnnotationInstance;
import org.jboss.jandex.AnnotationTarget;
import org.jboss.jandex.AnnotationTarget.Kind;
import org.jboss.jandex.AnnotationValue;
import org.jboss.jandex.ClassInfo;
import org.jboss.jandex.DotName;
import org.jboss.jandex.Type;

import com.tanwir.miniquarkus.processor.DotNames;

/**
 * Reproducibility utility class following Quarkus ARC patterns.
 * Ensures consistent ordering of generated bytecode for reproducible builds.
 */
public class Reproducibility {

    /**
     * Returns annotations in a consistent order for reproducible builds.
     */
    public static List<AnnotationInstance> orderedAnnotations(Set<AnnotationInstance> annotations) {
        if (annotations.isEmpty()) {
            return Collections.emptyList();
        }

        List<AnnotationInstance> sorted = new ArrayList<>(annotations);
        sorted.sort(createAnnotationComparator());
        return sorted;
    }

    /**
     * Returns annotation instances in a consistent order.
     */
    public static List<AnnotationInstance> orderedAnnotationProxies(Set<AnnotationInstance> proxies) {
        if (proxies.isEmpty()) {
            return Collections.emptyList();
        }

        List<AnnotationInstance> sorted = new ArrayList<>(proxies);
        sorted.sort(createAnnotationProxyComparator());
        return sorted;
    }

    /**
     * Returns types in a consistent order for reproducible builds.
     */
    public static List<Type> orderedTypes(Set<Type> types) {
        if (types.isEmpty()) {
            return Collections.emptyList();
        }

        List<Type> sorted = new ArrayList<>(types);
        sorted.sort(createTypeComparator());
        return sorted;
    }

    /**
     * Returns stereotypes in a consistent order for reproducible builds.
     */
    public static List<AnnotationInstance> orderedStereotypes(Set<AnnotationInstance> stereotypes) {
        if (stereotypes.isEmpty()) {
            return Collections.emptyList();
        }

        List<AnnotationInstance> sorted = new ArrayList<>(stereotypes);
        sorted.sort(createAnnotationComparator());
        return sorted;
    }

    /**
     * Returns injection points in a consistent order for reproducible builds.
     */
    public static List<org.jboss.jandex.Type> orderedInjectionPoints(List<org.jboss.jandex.Type> injectionPoints) {
        if (injectionPoints.isEmpty()) {
            return Collections.emptyList();
        }

        List<org.jboss.jandex.Type> sorted = new ArrayList<>(injectionPoints);
        sorted.sort(createTypeComparator());
        return sorted;
    }

    /**
     * Creates a comparator for annotations that ensures reproducible ordering.
     */
    private static Comparator<AnnotationInstance> createAnnotationComparator() {
        return (a1, a2) -> {
            // Compare by annotation name first
            int nameCompare = a1.name().toString().compareTo(a2.name().toString());
            if (nameCompare != 0) {
                return nameCompare;
            }

            // Then by target kind
            int targetCompare = compareTargetKind(a1.target().kind(), a2.target().kind());
            if (targetCompare != 0) {
                return targetCompare;
            }

            // Finally by string representation for stability
            return a1.toString().compareTo(a2.toString());
        };
    }

    /**
     * Creates a comparator for annotation proxies that ensures reproducible ordering.
     */
    private static Comparator<AnnotationInstance> createAnnotationProxyComparator() {
        return (p1, p2) -> {
            // Compare by annotation name
            int nameCompare = p1.name().toString().compareTo(p2.name().toString());
            if (nameCompare != 0) {
                return nameCompare;
            }

            // Then by string representation for stability
            return p1.toString().compareTo(p2.toString());
        };
    }

    /**
     * Creates a comparator for types that ensures reproducible ordering.
     */
    private static Comparator<Type> createTypeComparator() {
        return (t1, t2) -> {
            // Compare by type name
            int nameCompare = t1.name().toString().compareTo(t2.name().toString());
            if (nameCompare != 0) {
                return nameCompare;
            }

            // Then by kind
            int kindCompare = t1.kind().compareTo(t2.kind());
            if (kindCompare != 0) {
                return kindCompare;
            }

            // Finally by string representation for stability
            return t1.toString().compareTo(t2.toString());
        };
    }

    /**
     * Compares annotation target kinds for consistent ordering.
     */
    private static int compareTargetKind(AnnotationTarget.Kind kind1, AnnotationTarget.Kind kind2) {
        // Define consistent ordering of target kinds
        List<AnnotationTarget.Kind> order = List.of(
            AnnotationTarget.Kind.TYPE,
            AnnotationTarget.Kind.FIELD,
            AnnotationTarget.Kind.METHOD,
            AnnotationTarget.Kind.PARAMETER,
            AnnotationTarget.Kind.CONSTRUCTOR,
            AnnotationTarget.Kind.LOCAL_VARIABLE,
            AnnotationTarget.Kind.ANNOTATION_TYPE,
            AnnotationTarget.Kind.TYPE_PARAMETER,
            AnnotationTarget.Kind.TYPE_USE,
            AnnotationTarget.Kind.RECORD_COMPONENT,
            AnnotationTarget.Kind.MODULE
        );

        return Integer.compare(order.indexOf(kind1), order.indexOf(kind2));
    }

    /**
     * Creates a reproducible set of types.
     */
    public static <T> Set<T> reproducibleSet() {
        return Collections.unmodifiableSet(new TreeSet<>());
    }

    /**
     * Creates a reproducible list of types.
     */
    public static <T> List<T> reproducibleList() {
        return Collections.unmodifiableList(new ArrayList<>());
    }

    /**
     * Gets annotation values in a consistent order.
     */
    public static List<AnnotationValue> getAnnotationValues(AnnotationInstance annotation) {
        if (annotation.values() == null || annotation.values().isEmpty()) {
            return Collections.emptyList();
        }

        List<AnnotationValue> values = new ArrayList<>(annotation.values());
        values.sort((v1, v2) -> v1.name().compareTo(v2.name()));
        return values;
    }

    /**
     * Prevent instantiation.
     */
    private Reproducibility() {
        throw new UnsupportedOperationException("Utility class");
    }
}
