package com.tanwir.panache;

import org.jboss.logging.Logger;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;

/**
 * Thread-local JDBC transaction manager.
 *
 * <p>Mirrors the role of {@code io.quarkus.narayana.jta} in real Quarkus — but uses
 * plain JDBC connections instead of JTA. Each thread can have at most one active
 * transaction at a time (the most common case for request-scoped HTTP handling).
 *
 * <h2>How it works</h2>
 * <ol>
 *   <li>{@link #begin} opens a {@link Connection}, disables auto-commit, and stores it
 *       in a {@link ThreadLocal}.</li>
 *   <li>{@link MiniRepositoryBase} checks {@link #currentConnection} before every
 *       operation — if a connection is active it participates in the existing transaction;
 *       otherwise it borrows an auto-commit connection from the {@link DataSource}.</li>
 *   <li>{@link #commit}/{@link #rollback} close the connection and clear the ThreadLocal.</li>
 * </ol>
 *
 * <p>This pattern is exactly what Hibernate ORM does internally — each Hibernate session
 * holds a reference to the current JDBC connection, and JTA synchronisation determines
 * when it flushes and closes. Mini-quarkus simplifies by managing the connection directly.
 *
 * <h2>Usage in generated route handlers (from @Transactional)</h2>
 * <pre>{@code
 * // generated by MiniResteasyReactiveProcessor when @Transactional is detected
 * TransactionManager.begin();
 * try {
 *     Object result = resource.createProduct(body.mapTo(Product.class));
 *     TransactionManager.commit();
 *     routingContext.response().end(Json.encode(result));
 * } catch (Exception e) {
 *     TransactionManager.rollback();
 *     routingContext.fail(500, e);
 * }
 * }</pre>
 */
public final class TransactionManager {

    private static final Logger LOG = Logger.getLogger(TransactionManager.class);
    private static final ThreadLocal<Connection> CURRENT = new ThreadLocal<>();

    private TransactionManager() {}

    /**
     * Begins a new transaction on the current thread using the configured datasource.
     *
     * @throws IllegalStateException if a transaction is already active on this thread
     */
    public static void begin() {
        if (CURRENT.get() != null) {
            throw new IllegalStateException(
                    "A transaction is already active on this thread. "
                    + "Nested transactions are not supported.");
        }
        DataSource ds = MiniPanacheContext.getDataSource();
        if (ds == null) {
            throw new IllegalStateException(
                    "No DataSource configured. Ensure panache is initialized before using @Transactional.");
        }
        try {
            Connection conn = ds.getConnection();
            conn.setAutoCommit(false);
            CURRENT.set(conn);
            LOG.debug("[tx] Transaction begun");
        } catch (SQLException e) {
            throw new RuntimeException("Failed to begin transaction", e);
        }
    }

    /**
     * Commits the current transaction and releases the connection.
     *
     * @throws IllegalStateException if no transaction is active on this thread
     */
    public static void commit() {
        Connection conn = requireActive();
        try {
            conn.commit();
            LOG.debug("[tx] Transaction committed");
        } catch (SQLException e) {
            throw new RuntimeException("Failed to commit transaction", e);
        } finally {
            closeAndClear(conn);
        }
    }

    /**
     * Rolls back the current transaction and releases the connection.
     * Safe to call even if commit already succeeded (no-op in that case).
     */
    public static void rollback() {
        Connection conn = CURRENT.get();
        if (conn == null) return;
        try {
            conn.rollback();
            LOG.debug("[tx] Transaction rolled back");
        } catch (SQLException e) {
            LOG.warnf("[tx] Rollback failed: %s", e.getMessage());
        } finally {
            closeAndClear(conn);
        }
    }

    /**
     * Returns the active transaction connection, or {@code null} if no transaction is active.
     * Called by {@link MiniRepositoryBase} before each operation.
     */
    public static Connection currentConnection() {
        return CURRENT.get();
    }

    /**
     * Executes {@code block} within a new transaction.
     * Commits on success, rolls back on any exception.
     */
    public static void inTransaction(Runnable block) {
        begin();
        try {
            block.run();
            commit();
        } catch (Exception e) {
            rollback();
            if (e instanceof RuntimeException re) throw re;
            throw new RuntimeException(e);
        }
    }

    /**
     * Executes {@code block} within a new transaction and returns its result.
     */
    public static <T> T inTransaction(java.util.function.Supplier<T> block) {
        begin();
        try {
            T result = block.get();
            commit();
            return result;
        } catch (Exception e) {
            rollback();
            if (e instanceof RuntimeException re) throw re;
            throw new RuntimeException(e);
        }
    }

    private static Connection requireActive() {
        Connection conn = CURRENT.get();
        if (conn == null) {
            throw new IllegalStateException(
                    "No active transaction on this thread. Call TransactionManager.begin() first.");
        }
        return conn;
    }

    private static void closeAndClear(Connection conn) {
        CURRENT.remove();
        try {
            conn.close();
        } catch (SQLException e) {
            LOG.warnf("[tx] Failed to close connection: %s", e.getMessage());
        }
    }
}
